apiVersion: v1
kind: ConfigMap
metadata:
  name: logstash-configmap
data:
  logstash.yml: |
    http.host: "0.0.0.0"
    path.config: /usr/share/logstash/pipeline
  logstash.conf: |
    input {
        tcp {
            port => 4560
            codec => json_lines
        }
    }

    output {
      elasticsearch {
          hosts => [ "elasticsearch:9200" ]
          index => "logs"
          id => "logs_pipeline_id"
      }
    }