apiVersion: apps/v1
kind: Deployment
metadata:
  name: service1-deployment
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "8080"
    prometheus.io/path: "/actuator/prometheus"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service1
  template:
    metadata:
     labels:
       app: service1
    spec:
      containers:
        - image: service1:0.1
          imagePullPolicy: Never
          name: service1
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: service1-config
            - secretRef:
                name: service1-secret
